-- --------------------------------------------------------
-- Hôte :                        localhost
-- Version du serveur:           5.7.24 - MySQL Community Server (GPL)
-- SE du serveur:                Win64
-- HeidiSQL Version:             10.2.0.5599
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Listage des données de la table deuit-ta.blog : ~8 rows (environ)
/*!40000 ALTER TABLE `blog` DISABLE KEYS */;
INSERT INTO `blog` (`id`, `titleFR`, `titleBZH`, `excerptFR`, `excerptBZH`, `img`, `contentFR`, `contentBZH`, `created_at`) VALUES
	(32, 'Fête à Saint-Malo', 'Gouel e Sant-Malo', 'Une occasion de parler le breton au bord de la mer !', 'Ur chañs da gomz brezhoneg war bord ar mor !', '62a1fabd1e1289.71144268.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quodsi ipsam honestatem undique pertectam atque absolutam. Age sane, inquam. Facillimum id quidem est, inquam. Re mihi non aeque satisfacit, et quidem locis pluribus. \r\n\r\nDuo Reges: constructio interrete. Polycratem Samium felicem appellabant. Nemo nostrum istius generis asotos iucunde putat vivere. Polycratem Samium felicem appellabant. Quid enim est a Chrysippo praetermissum in Stoicis? Sed fac ista esse non inportuna; Qui ita affectus, beatum esse numquam probabis; Nihil ad rem! Ne sit sane; \r\n\r\nAn eiusdem modi? Negare non possum. Quam ob rem tandem, inquit, non satisfacit? Cyrenaici quidem non recusant; \r\n\r\nNunc omni virtuti vitium contrario nomine opponitur. Cave putes quicquam esse verius. Quid turpius quam sapientis vitam ex insipientium sermone pendere? Et quidem, inquit, vehementer errat; \r\n\r\nIta credo. Dici enim nihil potest verius. Tum Triarius: Posthac quidem, inquit, audacius. Eademne, quae restincta siti? Quod quidem nobis non saepe contingit. Igitur neque stultorum quisquam beatus neque sapientium non beatus. Praeteritis, inquit, gaudeo. \r\n\r\n', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ad bona praeterita redeamus. Ad eos igitur converte te, quaeso. Invidiosum nomen est, infame, suspectum. Duo Reges: constructio interrete. Si quicquam extra virtutem habeatur in bonis. Bonum integritas corporis: misera debilitas. \r\n\r\nAt enim hic etiam dolore. Graccho, eius fere, aequalí? Nulla erit controversia. Bonum integritas corporis: misera debilitas. Quis istud possit, inquit, negare? Sedulo, inquam, faciam. \r\n\r\nDuarum enim vitarum nobis erunt instituta capienda. At enim sequor utilitatem. Etiam beatissimum? De hominibus dici non necesse est. \r\n\r\nQui ita affectus, beatum esse numquam probabis; At iste non dolendi status non vocatur voluptas. Duo enim genera quae erant, fecit tria. Nam de isto magna dissensio est. \r\n\r\nIlli enim inter se dissentiunt. Solum praeterea formosum, solum liberum, solum civem, stultost; Quid me istud rogas? Quae contraria sunt his, malane? Quis istud, quaeso, nesciebat? \r\n\r\n', '2022-06-08 22:15:01'),
	(33, 'Feux d&#039;artifice au Drennec', 'Tanioù-arvest war an Drennec', 'Bonne ambiance sous les étoiles !', 'Aerglec&#039;h mad dindan ar stered !', '62a106da4dcb44.18579269.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quo tandem modo? Duo Reges: constructio interrete. Ut optime, secundum naturam affectum esse possit. Immo alio genere; Quae similitudo in genere etiam humano apparet. Nihil ad rem! Ne sit sane; \r\n\r\nAge, inquies, ista parva sunt. Minime vero, inquit ille, consentit. \r\n\r\nQuis enim redargueret? Non potes, nisi retexueris illa. Ita nemo beato beatior. Itaque contra est, ac dicitis; Et quidem, inquit, vehementer errat; Bestiarum vero nullum iudicium puto. \r\n\r\nNihil enim hoc differt. Frater et T. Luxuriam non reprehendit, modo sit vacua infinita cupiditate et timore. Tum Triarius: Posthac quidem, inquit, audacius. \r\n\r\nNon est ista, inquam, Piso, magna dissensio. Quae similitudo in genere etiam humano apparet. Nam ista vestra: Si gravis, brevis; Fortemne possumus dicere eundem illum Torquatum? \r\n\r\n', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Beatum, inquit. Respondeat totidem verbis. Ita ne hoc quidem modo paria peccata sunt. Sit enim idem caecus, debilis. \r\n\r\nRefert tamen, quo modo. Nescio quo modo praetervolavit oratio. Maximus dolor, inquit, brevis est. Hoc ipsum elegantius poni meliusque potuit. Quid me istud rogas? Torquatus, is qui consul cum Cn. Deinde dolorem quem maximum? \r\n\r\nSit sane ista voluptas. Qualem igitur hominem natura inchoavit? Res enim concurrent contrariae. Nam quid possumus facere melius? Audeo dicere, inquit. Bonum integritas corporis: misera debilitas. Istic sum, inquit. \r\n\r\nBeatus sibi videtur esse moriens. Stoici scilicet. Et harum quidem rerum facilis est et expedita distinctio. Omnia peccata paria dicitis. Hoc loco tenere se Triarius non potuit. \r\n\r\nParia sunt igitur. Duo Reges: constructio interrete. Qualem igitur hominem natura inchoavit? Quamquam tu hanc copiosiorem etiam soles dicere. Quis est tam dissimile homini. Et nemo nimium beatus est; \r\n\r\n', '2022-06-08 22:30:18'),
	(34, 'Contes en breton à Brennilis', 'Kontadennoù e brezhoneg e Brennilis', 'Découvrir les Monts d&#039;Arrée au travers des légendes.', 'Dizoleiñ ar Menez Are dre ar mojennoù.', '62a1093718db98.53405812.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Indicant pueri, in quibus ut in speculis natura cernitur. Cyrenaici quidem non recusant; Nunc vides, quid faciat. Sed ad bona praeterita redeamus. Omnis enim est natura diligens sui. Quare conare, quaeso. Duo Reges: constructio interrete. \r\n\r\nTum Triarius: Posthac quidem, inquit, audacius. Quorum altera prosunt, nocent altera. Cum id fugiunt, re eadem defendunt, quae Peripatetici, verba. Mihi, inquam, qui te id ipsum rogavi? \r\n\r\nIam enim adesse poterit. Hic ambiguo ludimur. Dici enim nihil potest verius. Tuo vero id quidem, inquam, arbitratu. Teneo, inquit, finem illi videri nihil dolere. In schola desinis. Sint ista Graecorum; \r\n\r\nItaque his sapiens semper vacabit. Restinguet citius, si ardentem acceperit. Quam illa ardentis amores excitaret sui! Cur tandem? Nam si amitti vita beata potest, beata esse non potest. Quare conare, quaeso. \r\n\r\nQuorum sine causa fieri nihil putandum est. Suo genere perveniant ad extremum; Erat enim Polemonis. Sed virtutem ipsam inchoavit, nihil amplius. Comprehensum, quod cognitum non habet? Sint modo partes vitae beatae. Quis enim redargueret? \r\n\r\n', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ante Aristippus, et ille melius. Duo Reges: constructio interrete. Sed quid sentiat, non videtis. Sed quid sentiat, non videtis. Sed ea mala virtuti magnitudine obruebantur. Hic ambiguo ludimur. \r\n\r\nVestri haec verecundius, illi fortasse constantius. Hoc mihi cum tuo fratre convenit. Nam Pyrrho, Aristo, Erillus iam diu abiecti. Hoc enim constituto in philosophia constituta sunt omnia. Aperiendum est igitur, quid sit voluptas; Idemque diviserunt naturam hominis in animum et corpus. \r\n\r\nSi longus, levis. Nos cum te, M. Avaritiamne minuis? Eademne, quae restincta siti? \r\n\r\nHos contra singulos dici est melius. Conferam avum tuum Drusum cum C. Cave putes quicquam esse verius. Sed haec nihil sane ad rem; Contineo me ab exemplis. \r\n\r\nParia sunt igitur. Omnes enim iucundum motum, quo sensus hilaretur. Sedulo, inquam, faciam. Sed ad bona praeterita redeamus. \r\n\r\n', '2022-06-08 22:40:23'),
	(35, 'Balades bretonnantes à Huelgoat', 'Pourmenadennoù brezhoneg en Uhelgoat', 'Découvrir la forêt et le breton en une sortie.', 'Dizoleiñ ar c&#039;hoad hag ar brezhoneg ', '62a10bac7889c7.66490811.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Idem iste, inquam, de voluptate quid sentit? Quis hoc dicit? Nihil sane. Tamen a proposito, inquam, aberramus. Ita relinquet duas, de quibus etiam atque etiam consideret. \r\n\r\nNon igitur bene. Duo Reges: constructio interrete. Haeret in salebra. Non potes, nisi retexueris illa. Ut pulsi recurrant? \r\n\r\nQuis enim redargueret? Cur deinde Metrodori liberos commendas? Easdemne res? Quamquam haec quidem praeposita recte et reiecta dicere licebit. Ait enim se, si uratur, Quam hoc suave! dicturum. Quid enim? \r\n\r\nId Sextilius factum negabat. Quo tandem modo? Id enim natura desiderat. Quis non odit sordidos, vanos, leves, futtiles? Sed nimis multa. Aliter homines, aliter philosophos loqui putas oportere? Estne, quaeso, inquam, sitienti in bibendo voluptas? \r\n\r\nHoc Hieronymus summum bonum esse dixit. Nihilo beatiorem esse Metellum quam Regulum. Nescio quo modo praetervolavit oratio. Duo enim genera quae erant, fecit tria. Post enim Chrysippum eum non sane est disputatum. Poterat autem inpune; Falli igitur possumus. \r\n\r\n', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mihi, inquam, qui te id ipsum rogavi? Neutrum vero, inquit ille. Odium autem et invidiam facile vitabis. Duo Reges: constructio interrete. Sullae consulatum? Egone quaeris, inquit, quid sentiam? \r\n\r\nIta graviter et severe voluptatem secrevit a bono. At iste non dolendi status non vocatur voluptas. Non laboro, inquit, de nomine. \r\n\r\nQuis hoc dicit? Bonum valitudo: miser morbus. At coluit ipse amicitias. Quae cum dixisset, finem ille. Summus dolor plures dies manere non potest? \r\n\r\nVidesne quam sit magna dissensio? Iam in altera philosophiae parte. At, si voluptas esset bonum, desideraret. Illis videtur, qui illud non dubitant bonum dicere -; Bestiarum vero nullum iudicium puto. Sullae consulatum? At enim hic etiam dolore. \r\n\r\nUt id aliis narrare gestiant? Efficiens dici potest. Negare non possum. Universa enim illorum ratione cum tota vestra confligendum puto. Nulla erit controversia. Quid enim? \r\n\r\n', '2022-06-08 22:50:52'),
	(36, 'Pêche à pied en breton', 'Loc&#039;heta e brezhoneg', 'A Crozon, comme autrefois.', 'E Kraozon, evel gwechall.', '62a11026e72fc5.85494538.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quid dubitas igitur mutare principia naturae? In schola desinis. Primum Theophrasti, Strato, physicum se voluit; Quid, quod res alia tota est? Scrupulum, inquam, abeunti; Conferam avum tuum Drusum cum C. Duo Reges: constructio interrete. Quis istum dolorem timet? \r\n\r\nVerum hoc idem saepe faciamus. Quo igitur, inquit, modo? Quae est igitur causa istarum angustiarum? Recte, inquit, intellegis. Philosophi autem in suis lectulis plerumque moriuntur. Quis enim redargueret? \r\n\r\nQuae quidem sapientes sequuntur duce natura tamquam videntes; Qui-vere falsone, quaerere mittimus-dicitur oculis se privasse; Etiam beatissimum? Non laboro, inquit, de nomine. Sed quid attinet de rebus tam apertis plura requirere? Sed haec in pueris; Quamquam id quidem, infinitum est in hac urbe; Quae duo sunt, unum facit. \r\n\r\nUbi ut eam caperet aut quando? Habes, inquam, Cato, formam eorum, de quibus loquor, philosophorum. Utilitatis causa amicitia est quaesita. Si quicquam extra virtutem habeatur in bonis. Traditur, inquit, ab Epicuro ratio neglegendi doloris. \r\n\r\nSint ista Graecorum; Consequentia exquirere, quoad sit id, quod volumus, effectum. Mihi quidem Antiochum, quem audis, satis belle videris attendere. Non laboro, inquit, de nomine. Ubi ut eam caperet aut quando? Nescio quo modo praetervolavit oratio. \r\n\r\n', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in rebus apertissimis nimium longi sumus. Sed haec nihil sane ad rem; Eadem fortitudinis ratio reperietur. Duo Reges: constructio interrete. \r\n\r\nPrimum divisit ineleganter; Nihil opus est exemplis hoc facere longius. Philosophi autem in suis lectulis plerumque moriuntur. Cupiditates non Epicuri divisione finiebat, sed sua satietate. \r\n\r\nAvaritiamne minuis? Non laboro, inquit, de nomine. \r\n\r\nIn schola desinis. Neutrum vero, inquit ille. Hoc non est positum in nostra actione. Ait enim se, si uratur, Quam hoc suave! dicturum. \r\n\r\nQui-vere falsone, quaerere mittimus-dicitur oculis se privasse; Videsne quam sit magna dissensio? Quod cum dixissent, ille contra. Videsne quam sit magna dissensio? Aliter homines, aliter philosophos loqui putas oportere? Quod equidem non reprehendo; Ac tamen hic mallet non dolere. \r\n\r\n', '2022-06-08 23:09:59'),
	(37, 'Soirées en breton rue de la soif', 'Nozvezhioù e brezhoneg war straed ar sec&#039;hed', 'Ambiance garantie dans la capitale de Bretagne !', 'Aerglec&#039;h gwaranted er gêr-benn Breizh !', '62a1f851ded3e3.36835750.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Qualem igitur hominem natura inchoavit? Restinguet citius, si ardentem acceperit. Age, inquies, ista parva sunt. Vide, quantum, inquam, fallare, Torquate. Duo Reges: constructio interrete. \r\n\r\nSed potestne rerum maior esse dissensio? Ita prorsus, inquam; Maximus dolor, inquit, brevis est. Pisone in eo gymnasio, quod Ptolomaeum vocatur, unaque nobiscum Q. \r\n\r\nHic ambiguo ludimur. Qualem igitur hominem natura inchoavit? Nulla erit controversia. Quid censes in Latino fore? \r\n\r\nSedulo, inquam, faciam. Tum ille: Ain tandem? Sed residamus, inquit, si placet. Bestiarum vero nullum iudicium puto. Sumenda potius quam expetenda. Verum hoc idem saepe faciamus. \r\n\r\nQuis enim redargueret? Quam illa ardentis amores excitaret sui! Cur tandem? Qualem igitur hominem natura inchoavit? An hoc usque quaque, aliter in vita? Summus dolor plures dies manere non potest? Ut id aliis narrare gestiant? Suam denique cuique naturam esse ad vivendum ducem. \r\n\r\n', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Collige omnia, quae soletis: Praesidium amicorum. Cur post Tarentum ad Archytam? Duo Reges: constructio interrete. Estne, quaeso, inquam, sitienti in bibendo voluptas? \r\n\r\nSatis est ad hoc responsum. Non laboro, inquit, de nomine. Conferam avum tuum Drusum cum C. Easdemne res? \r\n\r\nQue Manilium, ab iisque M. Quo modo autem philosophus loquitur? Ne discipulum abducam, times. Sed haec in pueris; Compensabatur, inquit, cum summis doloribus laetitia. Si qua in iis corrigere voluit, deteriora fecit. \r\n\r\nIllum mallem levares, quo optimum atque humanissimum virum, Cn. Itaque his sapiens semper vacabit. Aliter autem vobis placet. Nihil sane. Nihilo magis. Quid, si etiam iucunda memoria est praeteritorum malorum? \r\n\r\nHuius, Lyco, oratione locuples, rebus ipsis ielunior. Et quod est munus, quod opus sapientiae? Sed quod proximum fuit non vidit. Atqui reperies, inquit, in hoc quidem pertinacem; Zenonis est, inquam, hoc Stoici. Compensabatur, inquit, cum summis doloribus laetitia. Scrupulum, inquam, abeunti; Sed plane dicit quod intellegit. \r\n\r\n', '2022-06-09 15:40:33'),
	(38, 'Le retour des Jeudis du Port', 'Distro Yaouvezhioù ar Porzh', 'Les festivités reprennent au port de Brest !', 'Kregiñ a reont ar gouelioù en-dro e porzh Brest !', '62a1f9983cc1c1.57883427.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Dici enim nihil potest verius. Non enim iam stirpis bonum quaeret, sed animalis. Quaerimus enim finem bonorum. Quid Zeno? Quis istum dolorem timet? Non potes, nisi retexueris illa. Dicimus aliquem hilare vivere; Duo Reges: constructio interrete. \r\n\r\nPrimum quid tu dicis breve? Sed nimis multa. Paria sunt igitur. Nam quid possumus facere melius? \r\n\r\nQuid ergo hoc loco intellegit honestum? Simus igitur contenti his. Sed plane dicit quod intellegit. Hos contra singulos dici est melius. \r\n\r\nAge sane, inquam. Sint modo partes vitae beatae. Tibi hoc incredibile, quod beatissimum. Ne amores quidem sanctos a sapiente alienos esse arbitrantur. \r\n\r\nUtilitatis causa amicitia est quaesita. Iubet igitur nos Pythius Apollo noscere nosmet ipsos. Esse enim quam vellet iniquus iustus poterat inpune. \r\n\r\n', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Bonum incolumis acies: misera caecitas. Sed ad bona praeterita redeamus. Sint ista Graecorum; Duo Reges: constructio interrete. Quis enim redargueret? \r\n\r\nNegat esse eam, inquit, propter se expetendam. Deinde dolorem quem maximum? Quis negat? \r\n\r\nQuid, quod res alia tota est? An nisi populari fama? \r\n\r\nLaboro autem non sine causa; Et quidem, inquit, vehementer errat; Et ille ridens: Video, inquit, quid agas; Quae diligentissime contra Aristonem dicuntur a Chryippo. Age, inquies, ista parva sunt. \r\n\r\nPrioris generis est docilitas, memoria; Ego vero isti, inquam, permitto. Sit enim idem caecus, debilis. Torquatus, is qui consul cum Cn. Istam voluptatem, inquit, Epicurus ignorat? \r\n\r\n', '2022-06-09 15:46:00'),
	(39, 'La Fête du Bruit à Landerneau', 'Gouel an Trouz e Landerne', 'Un programme de qualité au bord de l&#039;Elorn !', 'Ur programm a -feson war bord an Elorn !', '62a201b72e83e4.50602481.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Itaque contra est, ac dicitis; Sed ea mala virtuti magnitudine obruebantur. Bonum valitudo: miser morbus. Neminem videbis ita laudatum, ut artifex callidus comparandarum voluptatum diceretur. Non semper, inquam; \r\n\r\nQuid me istud rogas? Illi enim inter se dissentiunt. Nam ante Aristippus, et ille melius. Recte, inquit, intellegis. Quamquam tu hanc copiosiorem etiam soles dicere. \r\n\r\nAliud igitur esse censet gaudere, aliud non dolere. Duo Reges: constructio interrete. Itaque his sapiens semper vacabit. A mene tu? \r\n\r\nSed ne, dum huic obsequor, vobis molestus sim. Bestiarum vero nullum iudicium puto. Tollenda est atque extrahenda radicitus. Tum mihi Piso: Quid ergo? \r\n\r\nMaximus dolor, inquit, brevis est. Et ille ridens: Video, inquit, quid agas; Quis istud, quaeso, nesciebat? Conferam tecum, quam cuique verso rem subicias; Eaedem res maneant alio modo. Sin aliud quid voles, postea. \r\n\r\n', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Et non ex maxima parte de tota iudicabis? Nihil ad rem! Ne sit sane; Mihi, inquam, qui te id ipsum rogavi? Vide, quaeso, rectumne sit. Si longus, levis. Ut optime, secundum naturam affectum esse possit. Quodsi ipsam honestatem undique pertectam atque absolutam. Sequitur disserendi ratio cognitioque naturae; \r\n\r\nQuid de Platone aut de Democrito loquar? Et nemo nimium beatus est; Tum mihi Piso: Quid ergo? Tum mihi Piso: Quid ergo? Et quod est munus, quod opus sapientiae? \r\n\r\nDuo Reges: constructio interrete. Eaedem enim utilitates poterunt eas labefactare atque pervertere. Sequitur disserendi ratio cognitioque naturae; Etiam beatissimum? Non est igitur voluptas bonum. \r\n\r\nAt hoc in eo M. Cur id non ita fit? Recte, inquit, intellegis. Quo tandem modo? Proclivi currit oratio. Ita enim vivunt quidam, ut eorum vita refellatur oratio. \r\n\r\nNunc vides, quid faciat. Audeo dicere, inquit. Quid censes in Latino fore? Quorum sine causa fieri nihil putandum est. \r\n\r\n', '2022-06-09 16:20:39');
/*!40000 ALTER TABLE `blog` ENABLE KEYS */;

-- Listage des données de la table deuit-ta.comments : ~0 rows (environ)
/*!40000 ALTER TABLE `comments` DISABLE KEYS */;
/*!40000 ALTER TABLE `comments` ENABLE KEYS */;

-- Listage des données de la table deuit-ta.contact : ~0 rows (environ)
/*!40000 ALTER TABLE `contact` DISABLE KEYS */;
/*!40000 ALTER TABLE `contact` ENABLE KEYS */;

-- Listage des données de la table deuit-ta.users : ~1 rows (environ)
/*!40000 ALTER TABLE `users` DISABLE KEYS */;
INSERT INTO `users` (`id`, `username`, `mail`, `password`, `avatar`, `created_at`, `role`) VALUES
	(25, 'Admin', 'admin@admin.fr', '$2y$10$cJi.bU2kMgGcKyEW80KxVOFLlQWp/TLuHr12y1llUkKYDit11nLYG', 'blank.jpg', '2022-06-03 14:58:24', 1);
/*!40000 ALTER TABLE `users` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
